# Testing HTML, CSS, JS and Python code

#### [W3C Markup Validator](https://validator.w3.org/) detected the following errors:

  **Add a Product page**
    
  <img src="images/validators/html_error_add_product_page.jpg" alt="Result in W3C Markup Validator for Add Product page." width="200px" height="auto">

  In the code below, an input tag has two id attributes: id="new-image" and id="id_image" (see image below). 

  <img src="images/validators/add_product_page.jpg" alt="Add Product page source code." width="500px" height="auto">

  id="new-image" is used by a script, while id="id_image" is coming from "django/forms/widgets/attrs.html" (custom widget file).

  <img src="images/validators/custom_clearable_file_input.jpg" alt="custom_clearable_file_input.html screenshot." width="500px" height="auto">

  Considering that I do not have access to id="id_image" (being added automatically by the django/forms), I have tried to change an id attribute for "new-image" to a class attribute. However, I have further discovered that "django/forms/widgets/attrs.html" eventually also adds additional classes, which provokes a similar error having two class attributes (one added by me for "new-image", another from the widget file). That's why I have decided to leave the html validator error as it is. 

  Strangely, if the html code of the page is checked in Chrome DevTools, there is no such id="id_image" (thus there is no error). It appears if one accesses the code from "View page source* button in the browser.

  **Edit a Product page**

  <img src="images/validators/html_error_edit_product_page.jpg" alt="Result in W3C Markup Validator for Add Product page." width="500px" height="auto">

  Regarding the first error, the form for "Edit a Product* page is prefilled from the database, so the "bad" url is coming from there. The easiest way to resolve this error would be to prepend the URLS in my form with *https:*. Currently I should probably have something like this:
  ```
  <input type="url" name="api_featured_image" value="{{image.url}}">
  ```

  If I change that to:
  ```
  <input type="url" name="api_featured_image" value="https:{{image.url}}">
  ```
  then the url would be correctly formatted in the output and it should have passed validation.

  However, I have checked the files *edit_product.html* and *forms.py*, there are no input fields where I could modify values. It's probably automatically generated by django and the fix won't be straightforward. Secondly, I don't use those information (like "api_featured_image") for rendering the *Product Details* page, that's why I decided to leave the error as it is.

  The second error on *Edit a Product* page is the same one described above for *Add a Product* page. 

  **Shopping Bag page**

  <img src="images/validators/html_error_shopping_bag_page.jpg" alt="Result in W3C Markup Validator for Shopping Bag page." width="500px" height="auto">

  This is a bug carried over from Boutique Ado course walkthrough project. The same id is coming from desktop and mobile views rendering. Due to lack of time, I have decided to leave it as it is and fix it later.

  **All other page on the website**

  For all other pages in the project, html code passed validation successfully.
  
  <img src="images/validators/w3c-markup-validator.jpg" alt="Results in W3C Markup Validator." width="300px" height="auto">

---

#### [W3C CSS Validator](https://jigsaw.w3.org/css-validator/) did not detect any problem in the CSS code:

  <img src="images/validators/w3c-css-validator.jpg" alt="Results in W3C CSS Validator." width="300px" height="auto">

---

#### [JSHint](https://jshint.com/) did not detect any problem in the JavaScript code.

---

#### [PEP8 online](http://pep8online.com/) did not detect any problem in the Python code:

  <img src="images/validators/pep8-online.jpg" alt="Results in PEP8 online validator." width="200" height="auto">